{
 "title": "Main",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Thinkpad (192.168.0.111)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Production",
   "type": "stat",
   "description": "Checks if all node-exporter jobs are up, if 1 is down, returns 0.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{job=~\"kubernetes.*|node-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Production Up (days)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_time_seconds - node_boot_time_seconds) / 86400"
    }
   ]
  },
  {
   "title": "Pressure Production",
   "type": "bargauge",
   "description": "Resource pressure via PSI",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_pressure_cpu_waiting_seconds_total[$__rate_interval])",
     "legendFormat": "CPU"
    },
    {
     "expr": "irate(node_pressure_memory_waiting_seconds_total[$__rate_interval])",
     "legendFormat": "Mem"
    },
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total[$__rate_interval])",
     "legendFormat": "I/O"
    },
    {
     "expr": "irate(node_pressure_irq_stalled_seconds_total[$__rate_interval])",
     "legendFormat": "Irq"
    }
   ]
  },
  {
   "title": "Pod status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (phase) (kube_pod_status_phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Production Pods Uptime",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    { "expr": "time() - kube_pod_start_time", "legendFormat": "{{namespace}} {{pod}}" },
    { "legendFormat": "{{namespace}} {{pod}}" }
   ]
  }
 ]
}