apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/homepage

patches:
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: homepage
        namespace: homepage
      data:
        services.yaml: |
          - Monitoring:
              - Grafana:
                  href: http://192.168.0.109:30030
                  icon: grafana.png
              - Prometheus:
                  href: http://192.168.0.109:30090
                  icon: prometheus.png
              - Alertmanager:
                  href: http://192.168.0.109:30093
                  icon: alertmanager.png

          - Media:
              - Jellyfin:
                  href: http://192.168.0.109:30096
                  icon: jellyfin.png