apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/grafana
patches:
  - target:
      kind: Deployment
      name: grafana
    patch: |
      - op: remove
        path: /spec/template/spec/initContainers
      - op: replace
        path: /spec/template/spec/volumes/0
        value:
          name: data
          persistentVolumeClaim:
            claimName: grafana-data
  - target:
      kind: PersistentVolumeClaim
      name: grafana-data
    patch: |
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: grafana-data
        namespace: monitoring
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: nfs-config
        resources:
          requests:
            storage: 2Gi