apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/grafana
patches:
  - target:
      kind: Deployment
      name: grafana
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: grafana
      spec:
        replicas: 3