apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: homelab-l2-policy
spec:
  loadBalancerIPs: true
  interfaces:
  - ^ens.*
  - ^eth.*
  nodeSelector:
    matchLabels: {}