apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: homelab-l2-policy
spec:
  loadBalancerIPs: true
  interfaces:
  - ^ens.*
  - ^eth.*
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
  externalIPs: true
  serviceSelector:
    matchLabels: {}