apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:sZ+nuN8eg6DW0sPh9jc2ZYzfzDCnnMH7dNq7m0i1H7LIKbUGbXLgsb17qUqDtU+LUT0XUCKsoIOJKcCHDhVpKEM6bs4mMjGZ8bAYrCXNnOtlIhUoQkCVrquVN9iyJ38go4sDd2ASlZ9+tseTfMiNQBnk3GPOJ0abW/FRUkTF9Wvy99hmvC+anZg+6uC3/ZfdPLZsBCleuesVdszsLwDxkV/7qXx2Oob5kktcGfr05dGO8zfyu3eiXA==,iv:WBvPmTWGsTjgtn9gJYFu3+2uz4WL/e5BowOUSD5qgRs=,tag:5E5Ein9yFcR3LvhiRgDp0A==,type:str]
sops:
    age:
        - recipient: age1t35sxk7cxkxk0rgfdmnkcnvky7zuf7g9407d3s03qyggu3w62adqnst5ya
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1czhpQ2JTcTYxa1ZYQ0F0
            Wkd2OXBSS2hpUW0rTlZlc0NwNFVOMWRvOFdJCkZLNDI3bWN4MDN1MTNhTkhqMXB1
            cnBEMXp1ZFFZUXg2SFM4N1VKVTZnUEEKLS0tIDBhL2FMYXlRdHJteWROUmhzNDVs
            bndwalVrTURkSTdZWWErWmF4SDl1QTAKjXYcA7jP5qoae7gFS43+kcT4EFnVpZ9Q
            6ZLaCrq0ucuJE+EHQHXfNkXt6W7Pj/D+gIJuDTX/i1rOAfEe36jmjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T10:49:39Z"
    mac: ENC[AES256_GCM,data:VqayZvz9KTITNgvV5lGzewsemjTmvZPZ3W/9nawI9biVjPX+OpFUA9SbdJHyEuxgiyQdVaIWgVaxH29ITTuHx0Hrv9mQECteJj/K6QiAMSZFZEYti8FjJgNnI+VP3Dz69ODDQ/lteF2uzIHYBYTRWY8d6KKb4vsJwGn7ASxTyog=,iv:X2r6H2LpV2paQgn383erPZkRTzLYEJqknfGeowseH8U=,tag:ij/izeHcFxuV+o6YIXTutw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
